[env]
TERM = "xterm-256color"

[window]
padding.x = 12
padding.y = 12

decorations = "Buttonless"

opacity = 0.5
blur = true

option_as_alt = "Both"

[font]
normal.family = "FiraCode Nerd Font Mono"

size = 16

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]
